name: service_common
description: Shared utilities, infrastructure, and middleware for Microservices.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  dart_frog: ^1.1.0
  mysql_client_plus: ^0.1.2
  redis: ^3.0.0
  logging: ^1.3.0
  dotenv: ^4.2.0
  dart_jsonwebtoken: ^3.3.1
  basic_utils: ^5.8.2
  pointycastle: ^4.0.0
  uuid: ^4.5.2
  http: ^1.1.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
